import type { SpirographParams } from "./types";

export type Preset = Partial<SpirographParams>;

export const BUILT_IN_PRESETS: Record<string, Preset> = {
  "Classic Spirograph": {
    arm1Radius: 280,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 180,
    arm2Speed: -3,
    arm2Phase: 0,
    arm3Enabled: false,
    arm4Enabled: false,
    radialOffset: 0,
    phaseOffset: 0,
    scaleOffset: 0,
    rotations: 1,
    animationMode: "Draw"
  },
  "Spiral Rose": {
    arm1Radius: 250,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 150,
    arm2Speed: 6,
    arm2Phase: 0,
    arm3Enabled: false,
    arm4Enabled: false,
    radialOffset: 3,
    phaseOffset: 2,
    scaleOffset: 0,
    rotations: 30,
    animationMode: "Draw"
  },
  "Concentric Waves": {
    arm1Radius: 200,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 80,
    arm2Speed: -7,
    arm2Phase: 0,
    arm3Radius: 40,
    arm3Speed: 17,
    arm3Phase: 0,
    arm3Enabled: true,
    arm4Enabled: false,
    radialOffset: 5,
    phaseOffset: 0,
    scaleOffset: 0,
    rotations: 40,
    animationMode: "Draw"
  },
  "Growing Flower": {
    arm1Radius: 150,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 100,
    arm2Speed: 5,
    arm2Phase: 0,
    arm3Enabled: false,
    arm4Enabled: false,
    radialOffset: 0,
    phaseOffset: 0,
    scaleOffset: 0.02,
    rotations: 25,
    animationMode: "Draw"
  },
  "Hypnotic Spiral": {
    arm1Radius: 200,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 100,
    arm2Speed: -8,
    arm2Phase: 0,
    arm3Radius: 50,
    arm3Speed: 15,
    arm3Phase: 0,
    arm3Enabled: true,
    arm4Enabled: false,
    radialOffset: 2,
    phaseOffset: 5,
    scaleOffset: 0.005,
    rotations: 50,
    animationMode: "Draw"
  },
  "Phase Animation": {
    arm1Radius: 280,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 180,
    arm2Speed: -5,
    arm2Phase: 0,
    arm3Enabled: false,
    arm4Enabled: false,
    radialOffset: 0,
    phaseOffset: 0,
    scaleOffset: 0,
    rotations: 1,
    animationMode: "Animate Phase",
    animPhaseFrom: 0,
    animPhaseTo: Math.PI * 2,
    animLoopMode: "Ping-Pong"
  },
  "Breathing Spiral": {
    arm1Radius: 250,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 120,
    arm2Speed: 7,
    arm2Phase: 0,
    arm3Enabled: false,
    arm4Enabled: false,
    radialOffset: 0,
    phaseOffset: 0,
    scaleOffset: 0,
    rotations: 14,
    animationMode: "Animate Offset",
    animOffsetFrom: 0,
    animOffsetTo: 8,
    animLoopMode: "Ping-Pong"
  },
  "Morphing Pattern": {
    arm1Radius: 200,
    arm1Speed: 1,
    arm1Phase: 0,
    arm2Radius: 150,
    arm2Speed: -6,
    arm2Phase: 0,
    arm3Radius: 80,
    arm3Speed: 11,
    arm3Phase: 0,
    arm3Enabled: true,
    arm4Enabled: false,
    radialOffset: 0,
    phaseOffset: 0,
    scaleOffset: 0,
    rotations: 12,
    animationMode: "Animate All",
    animPhaseFrom: 0,
    animPhaseTo: Math.PI,
    animOffsetFrom: 0,
    animOffsetTo: 5,
    animScaleFrom: 0,
    animScaleTo: 0.02,
    animLoopMode: "Ping-Pong"
  }
};
