# Build stage
FROM oven/bun:1 AS base

WORKDIR /build

COPY . .

RUN bun install

# production stage
FROM caddy:alpine AS production-stage

COPY --from=build-stage /build/dist /srv

EXPOSE 4444

CMD ["bun", "start"]