# Build stage
FROM node:22-slim AS build-stage

WORKDIR /build

RUN corepack enable

RUN corepack prepare yarn@4.3.1 --activate

COPY package*.json yarn.lock .yarnrc.yml ./

RUN yarn install

COPY . .

RUN yarn build --sourcemap

# production stage
FROM caddy:alpine AS production-stage

COPY --from=build-stage /build/dist /srv

EXPOSE 4444