FROM node:22-slim

WORKDIR /app

RUN corepack enable

RUN corepack prepare yarn@4.6.0 --activate

COPY package*.json yarn.lock .yarnrc.yml ./

RUN yarn install

COPY . .

EXPOSE 4444

CMD ["yarn", "dev"]