services:
  kj-home:
    build:
      context: ../home
      dockerfile: ../docker/home/Dockerfile.dev
    container_name: kj_home
    volumes:
      - ../home:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "4444:4444"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    networks:
      - kj-network
    restart: always

networks:
  kj-network:
    