services:
  kj-home:
    build:
      context: ../home
      dockerfile: ../docker/home/Dockerfile.dev
    container_name: kj_home
    volumes:
      - ../home:/app
      - /home/node_modules
      - /home/.next
    ports:
      - "4444:4444"
    networks:
      - kj-network
    restart: always

networks:
  kj-network:
    