FROM node:20 AS base
WORKDIR /home
RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

FROM node:20-alpine3.19 as release
WORKDIR /home
RUN npm i -g pnpm

COPY --from=base /home/node_modules ./node_modules
COPY --from=base /home/package.json ./package.json
COPY --from=base /home/.next ./.next
COPY --from=base /home/app ./app
COPY --from=base /home .

EXPOSE 4444

CMD ["pnpm", "dev"]