FROM node:20 AS base
WORKDIR /blog
RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

FROM node:20-alpine3.19 as release
WORKDIR /blog
RUN npm i -g pnpm

COPY --from=base /blog/node_modules ./node_modules
COPY --from=base /blog/package.json ./package.json
COPY --from=base /blog/.next ./.next
COPY --from=base /blog/app ./app
COPY --from=base /blog .

EXPOSE 3000

CMD ["pnpm", "dev"]